### PR TITLE
Merge to upstream

### PR DESCRIPTION
**Pull request by Johongo**
Let me know if something is weird.

### CODE REVIEW

**Comment by Johongo** [comment]
Some squashing and it should be good to go.

**Comment by ollema** [comment]
I can't take a closer look right now but right off the bat I can say there are some Agari specific commits in here that should not be merged, like 504619717600073c444953f89277d443a50f7da2

**Comment by Johongo** [comment]
I have taken care of the Agari related commits, we just need to squash them:
(The last three fixes the first three.)

- Fix container tag (5046197)
- update wiki link (a9a157f)
- update message for untagged resources to point to agari wiki (cf5a7bc)
- Update Makefile (cd43563)
- Update templates.go (4574d8d)
- Update templates.go (0b5f99b)

**Comment by ollema** [comment]
okay, my bad!

**Comment by benjaminhartwell** [comment]
LGTM

**Pull request merged**
